logging:
  level:
    root: warn
    com.example.springtoy.api: debug

spring:
  profiles:
    active:
      on-profile: local
  datasource:
    password: rladudfo1
    url: jdbc:mysql://localhost:3306/spring_toy_project?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  url:
    base: http://localhost:8080


