logging:
  level:
    root: warn
    com.example.springtoy.api: info
    path: /home/ec2-user/api/log
    file:
      max-history: 7


spring:
  profiles: alpha
  datasource:
    password: XXXXXX
    url: jdbc:mysql://127.0.0.1:33060//spring_toy_project?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&usesSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: youngrae
    password: youngrae
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false
